#!/bin/sh
# Part of the MiClash package - installed to /etc/hotplug.d/net/99-clash-tun
#
# Reacts to mihomo creating the clash-tun device (ACTION=add) and immediately
# installs the ip route pointing to it. This is faster than waiting for the
# 30 s poll in service_started() and covers the normal startup path.

[ -x /opt/clash/bin/clash-rules ] || exit 0
[ ! -e /var/run/miclash/package-removal ] || exit 0

case "$ACTION" in
    add)
		[ ! -e /var/run/miclash/package-removal ] || exit 0
        [ "$INTERFACE" = "clash-tun" ] || exit 0
		[ -r /usr/share/miclash/mutation-lock.sh ] || exit 1
		. /usr/share/miclash/mutation-lock.sh || exit 1
		miclash_mutation_lock_enter normal 30000 || exit $?
		trap 'miclash_mutation_lock_leave >/dev/null 2>&1 || true' EXIT
		trap 'exit 1' HUP INT TERM
        /opt/clash/bin/clash-rules tun_route_setup
        /opt/clash/bin/clash-rules repair_policy
        ;;
esac
