#!/bin/sh /etc/rc.common

START=12
STOP=88

[ -r /usr/share/miclash/mutation-lock.sh ] || return 1
. /usr/share/miclash/mutation-lock.sh || return 1

miclash_guard_locked() {
	mode=normal
	[ "${MICLASH_MUTATION_LOCK_PACKAGE:-0}" != 1 ] || mode=package
	miclash_mutation_lock_enter "$mode" 30000 || return $?
	"$@"
	result=$?
	miclash_mutation_lock_leave || return 1
	return "$result"
}

start_locked() {
	/usr/bin/ucode -L '/usr/share/*.uc' /usr/share/miclash/guard-bootstrap.uc install
}

start() { miclash_guard_locked start_locked; }

reload() {
	start
}

# Guard ownership intentionally outlives ordinary MiClash/Mihomo service stops.
stop() {
	return 0
}

remove_locked() {
	/usr/bin/ucode -L '/usr/share/*.uc' /usr/share/miclash/guard-bootstrap.uc remove
}

remove() { miclash_guard_locked remove_locked; }
