#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1
PACKAGE_REMOVAL_BARRIER="/var/run/miclash/package-removal"

start_service() {
	[ ! -e "$PACKAGE_REMOVAL_BARRIER" ] || return 1
	procd_open_instance
	procd_set_param command /usr/bin/ucode -L '/usr/share/*.uc' /usr/sbin/miclashd
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
	procd_open_instance telegram-poller
	procd_set_param command /usr/bin/ucode -L '/usr/share/*.uc' /usr/sbin/miclash-telegram-poller
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
